name: Demo dot Net có upload artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Show result
        run: dir

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./bin/Release
